<div class="card no-rationale square-cover apps small" data-docid="kr.com.efun.kok.google" data-original-classes="card no-rationale square-cover apps small" data-short-classes="card no-rationale square-cover apps tiny" data-thin-classes="card no-rationale square-cover apps small"> <div class="card-content id-track-click id-track-impression" data-docid="kr.com.efun.kok.google" data-server-cookie="CAIaNwoeEhwKFmtyLmNvbS5lZnVuLmtvay5nb29nbGUQARgDMhMI6MzTxqXY3gIVyIOWCh31KgYIQgA=" data-uitype="500">  <a class="card-click-target" data-server-cookie="CAIaNwoeEhwKFmtyLmNvbS5lZnVuLmtvay5nb29nbGUQARgDMhMI6MzTxqXY3gIVyIOWCh31KgYIQgA=" data-uitype="500" href="/store/apps/details?id=kr.com.efun.kok.google" aria-hidden="true" tabindex="-1"></a> <div class="cover"> <div class="cover-image-container"> <div class="cover-outer-align"> <div class="cover-inner-align"> <img alt="오크: 전쟁의 서막" class="cover-image" data-cover-large="//lh3.googleusercontent.com/cRTL6E9IlaxDSkfsfYqGxBYb8OXW_kNEKsVcr7hvpc3R9m6KBuMxNjdTIc_sjysnPSg=w340-rw" data-cover-small="//lh3.googleusercontent.com/cRTL6E9IlaxDSkfsfYqGxBYb8OXW_kNEKsVcr7hvpc3R9m6KBuMxNjdTIc_sjysnPSg=w170-rw" src="//lh3.googleusercontent.com/cRTL6E9IlaxDSkfsfYqGxBYb8OXW_kNEKsVcr7hvpc3R9m6KBuMxNjdTIc_sjysnPSg=w170-rw" aria-hidden="true"> </div> </div> </div> <a class="card-click-target" href="/store/apps/details?id=kr.com.efun.kok.google" aria-label="     오크: 전쟁의 서막    ">  <span class="movies preordered-overlay-container id-preordered-overlay-container" style="display:none"> <span class="preordered-label">선주문됨</span> </span> <span class="preview-overlay-container" data-docid="kr.com.efun.kok.google">  </span>  </a>  </div> <div class="details">  <a class="card-click-target" href="/store/apps/details?id=kr.com.efun.kok.google" aria-hidden="true" tabindex="-1"> </a>    <a class="title" href="/store/apps/details?id=kr.com.efun.kok.google" title="오크: 전쟁의 서막" aria-hidden="true" tabindex="-1">  오크: 전쟁의 서막 <span class="paragraph-end"></span> </a>    <div class="subtitle-container">   <a class="subtitle" href="/store/apps/dev?id=4757913198011400958" title="Efun Company">Efun Company</a>   <span class="price-container"> <span class="paragraph-end"></span>    </span> </div>  <div class="description">  108개의 직업, 전쟁을 바꾸다<br>판타지 MMORPG [오크: 전쟁의 서막]<br>그 위대한 여정에 지금바로 합류하세요. <span class="paragraph-end"></span>  <a class="card-click-target" href="/store/apps/details?id=kr.com.efun.kok.google" aria-hidden="true" tabindex="-1"> </a>   </div> </div>       <div class="reason-set">  <span class="stars-container"> <a href="/store/apps/details?id=kr.com.efun.kok.google"> <div class="reason-set-star-rating">  <div class="tiny-star star-rating-non-editable-container" aria-label="별표 5개 만점에 4.2개로 평가했습니다."> <div class="current-rating" jsname="jIIjq" style="width: 83.21318626403809%;"></div> </div>  </div> </a> <span class="price-container"> <span class="paragraph-end"></span>    </span>  </span> </div>   </div>   </div>


<!DOCTYPE html>
<html>
<head>
<meta charset=“UTF-8”>
<title>Insert title here</title>
</head>
<body>

</body>
</html>